arrowParens: avoid # Include parenthesis around a sole arrow function parameter,
semi: false # Specify if you want to print semicolons at the end of statements
singleQuote: true # If you want to use single quotes
trailingComma: es5 # Print trailing commas wherever possible when multi-line
