name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run build.ps1
        shell: pwsh
        run: ./build.ps1 -CI
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
